name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge checkout 
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
