name: Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      LOGGING_LOCATION: textalert.log
      GCP_PROJECT: 123456789
      TWILIO_FROM: +15005550006

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install pytest

    - name: checking test Coverage
      run: |
        coverage run -m pytest;coverage report -m; coverage html
